#!/bin/bash

sudo find -name "/home/*/web/*/public_html" -not -path "/home/*/web/*/public_html/wp-content/upolads" -type d -exec chmod 755 {} \; 
sudo find -name "/home/*/web/*/public_html" -not -path "/home/*/web/*/public_html/wp-content/upolads" -type f -exec chmod 644 {} \;
echo " - ";
echo "============================ All Dirs 755 / Files 644 Changed Successfully! (Excluded Uploads) =================";
echo " - ";

#sudo find /home/*/web/*/public_html/wp-content/uploads -type d -print0 | xargs -0 chmod 777
#sudo find /home/*/web/*/public_html/wp-content/uploads -type f -print0 | xargs -0 chmod 777
#echo " - ";
#echo "============================ All (Uploads) Dirs 777 / Files 777 Changed Successfully! =================";
#echo " - ";

sudo find -name "/home/admin/web/" -not -path "/home/*/web/*/public_html/wp-content/upolads" -exec chown -R admin:admin {} \; 
#sudo chown -R admin:admin /home/admin/web/ 

sudo find -name "/home/indiyaa/web/" -not -path "/home/*/web/*/public_html/wp-content/upolads" -exec chown -R indiyaa:indiyaa {} \;
#sudo chown -R indiyaa:indiyaa /home/indiyaa/web/

sudo find -name "/home/webtimiser/web/" -not -path "/home/*/web/*/public_html/wp-content/upolads" -exec chown -R webtimiser:webtimiser {} \;
#sudo chown -R webtimiser:webtimiser /home/webtimiser/web/
#ssh root@10.99.0.12 sudo find /home/*/web/*/public_html/wp-content/uploads -type d -print0 | xargs -0 chmod 777 
#ssh root@10.99.0.12 sudo find /home/*/web/*/public_html/wp-content/uploads -type f -print0 | xargs -0 chmod 777
ssh root@10.99.0.12 sudo chown -R www-data:www-data /home/admin/web/*/public_html/wp-content/uploads | xargs -0 chmod 777 

echo " - ";
echo "====================== 775-644-chown-user-user-exclude-uploads - All Finished Succeassfully! ================================";
echo " - ";

#
