#!/bin/bash

#set -x

sudo fallocate -l 4G /swapfile

ls -lh /swapfile

sudo chmod 600 /swapfile

ls -lh /swapfile

sudo mkswap /swapfile && sudo swapon /swapfile && sudo swapon -s

echo "======================================================="
echo "===========Follow Enabling the Swap File==============="
echo "======================================================="
  
#####
