#!/bin/bash

#set -x

cd /home/$client/web/$site/public_html/wp-content/themes/ && wget https://github.com/bigcloudcms/wpcloudcms/archive/master.tar.gz && tar xfz master.tar.gz && rm -f master.tar.gz
mkdir /home/$client/web/$site/public_html/wp-content/themes/wpcloudcms
mv -f wpcloudcms-master/* ./wpcloudcms 
rm -rf /home/$client/web/$site/public_html/wp-content/wpcloudcms-master* 

#####
