#!/bin/bash

#set -x
echo 'syncing virtue_premium theme from wpmaster.bigcloudcms.com...';
rsync -avz /home/admin/web/wpmaster.bigcloudcms.com/public_html/wp-content/themes/virtue_premium/ /home/$client/web/$site/public_html/wp-content/themes/virtue_premium/
echo'-'
echo'========================== virtue_premium Theme Updated Successfully! ================================='
echo'-'
echo 'Downloading WPCloudCMS Theme from github...';
rm -rf /home/$client/web/$site/public_html/wp-content/themes/wpcloudcms*
cd /home/$client/web/$site/public_html/wp-content/themes/ 
wget https://github.com/bigcloudcms/wpcloudcms/archive/master.tar.gz && tar xfz master.tar.gz && rm -f master.tar.gz
if [ -d /home/$client/web/$site/public_html/wp-content/themes/wpcloudcms ]; then echo 'wpcloudcms Exists';
cd /home/$client/web/$site/public_html/wp-content/themes/
tar -zcvf wpcloudcms.tar.gz wpcloudcms
else
  echo 'wpcloudcms Not Exist'; fi
mkdir /home/$client/web/$site/public_html/wp-content/themes/wpcloudcms
mv -f wpcloudcms-master/* ./wpcloudcms 
rm -rf /home/$client/web/$site/public_html/wp-content/themes/wpcloudcms-master* 
echo '-';
echo '========================== WPCloudCMS Child Theme Installed /Updated Successfully! =================================';
echo '-'; 
/home/scripts/775-644-chown-user-user-exclude-uploads
echo'-'
echo'========================== wpcloudcms child Theme Updated Successfully! ================================='
echo'-'
#####
