#!/bin/bash

#set -x
echo "syncing virtue_premium theme from wpmaster.bigcloudcms.com...";
rsync -avz /home/admin/web/wpmaster.bigcloudcms.com/public_html/wp-content/themes/virtue_premium/ /home/$client/web/$site/public_html/wp-content/themes/virtue_premium/
echo "-"
echo "========================== virtue_premium Theme Updated Successfully! ================================="
echo "-"
echo "Downloading WPCloudCMS Theme from github...";
rm -rf /home/$client/web/$site/public_html/wp-content/themes/wpcloudcms*
cd /home/$client/web/$site/public_html/wp-content/themes/ 
wget https://github.com/bigcloudcms/wpcloudcms/archive/master.tar.gz && tar xfz master.tar.gz && rm -f master.tar.gz
if [ -d /home/$client/web/$site/public_html/wp-content/themes/wpcloudcms ]; then echo 'wpcloudcms Exists';
cd /home/$client/web/$site/public_html/wp-content/themes/
tar -zcvf wpcloudcms.tar.gz wpcloudcms
else
  echo "wpcloudcms Not Exist"; fi
mkdir /home/$client/web/$site/public_html/wp-content/themes/wpcloudcms
mv -f wpcloudcms-master/* ./wpcloudcms 
rm -rf /home/$client/web/$site/public_html/wp-content/themes/wpcloudcms-master* 
echo "-";
echo "========================== WPCloudCMS Child Theme Installed /Updated Successfully! =================================";
echo "-"; 
echo "============================ Starting 775-644-chown-user-user-exclude-uploads ======================";
umount /home/$client/web/$site/public_html/wp-content/uploads
umount -a -t nfs
find "/home/$client/web/$site/public_html" -type d -not -path "/home/$client/web/$site/public_html/wp-content/uploads/*" -print0 | xargs -0 chmod 755 
find "/home/$client/web/$site/public_html" -type f -not -path "/home/$client/web/$site/public_html/wp-content/uploads/*" -print0 | xargs -0 chmod 644 
find "/home/$client/web/$site/public_html/wp-config-sample.php" -type f -print0 | xargs -0 chmod 775
chown -R $client:$client /home/$client/web/$site
find "/home/$client/web/$site/public_html" -type d -print0 | xargs -0 chmod 755 && find "/home/$client/web/$site/public_html" -type f -print0 | xargs -0 chmod 644 && find "/home/$client/web/$site/public_html/wp-config-sample.php" -type f -print0 | xargs -0 chmod 775 && chown -R $client:$client /home/$client/web/
#/home/scripts/775-644-chown-user-user-exclude-uploads
ssh root@10.99.0.12 sudo chown -R www-data:www-data /home/$client/web/$site/public_html/wp-content/uploads && sudo chmod 777 /home/$client/web/$site/public_html/wp-content/uploads

sudo find -name "/home/*/web/*/public_html" -not -path "/home/*/web/*/public_html/wp-content/upolads" -type d -exec chmod 755 {} \; 
sudo find -name "/home/*/web/*/public_html" -not -path "/home/*/web/*/public_html/wp-content/upolads" -type f -exec chmod 644 {} \;
echo " - ";
echo "============================ All Dirs 755 / Files 644 Changed Successfully! (Excluded Uploads) =================";
echo " - ";

#sudo find /home/*/web/*/public_html/wp-content/uploads -type d -print0 | xargs -0 chmod 777
#sudo find /home/*/web/*/public_html/wp-content/uploads -type f -print0 | xargs -0 chmod 777
#echo " - ";
#echo "============================ All (Uploads) Dirs 777 / Files 777 Changed Successfully! =================";
#echo " - ";

sudo find -name "/home/admin/web/" -not -path "/home/*/web/*/public_html/wp-content/upolads" -exec chown -R admin:admin {} \; 
#sudo chown -R admin:admin /home/admin/web/ 

sudo find -name "/home/indiyaa/web/" -not -path "/home/*/web/*/public_html/wp-content/upolads" -exec chown -R indiyaa:indiyaa {} \;
#sudo chown -R indiyaa:indiyaa /home/indiyaa/web/

sudo find -name "/home/webtimiser/web/" -not -path "/home/*/web/*/public_html/wp-content/upolads" -exec chown -R webtimiser:webtimiser {} \;
#sudo chown -R webtimiser:webtimiser /home/webtimiser/web/
#ssh root@10.99.0.12 sudo find /home/*/web/*/public_html/wp-content/uploads -type d -print0 | xargs -0 chmod 777 
#ssh root@10.99.0.12 sudo find /home/*/web/*/public_html/wp-content/uploads -type f -print0 | xargs -0 chmod 777
ssh root@10.99.0.12 sudo chown -R www-data:www-data /home/admin/web/*/public_html/wp-content/uploads && sudo chmod 777 /home/admin/web/*/public_html/wp-content/uploads
/home/scripts/mount-all-sites
echo " - ";
echo "====================== 775-644-chown-user-user-exclude-uploads - All Finished Succeassfully! ================================";
echo " - ";
echo " - ";
echo "========================== wpcloudcms child Theme Updated Successfully! =================================";
echo " - ";
#####
