#!/bin/bash

#set -x
rm -rf /home/scriptsbkup*
if [ -d /home/scripts ]; then echo 'scripts Exists'; 
mkdir /home/scriptsbkup 
mv /home/scripts/* /home/scriptsbkup 
rmdir /home/scripts
else
  echo 'Not found'; fi
cd /home 
wget https://github.com/bigcloudcms/wbmn-scripts/archive/master.tar.gz && tar xfz master.tar.gz && rm -f master.tar.gz 
mkdir -pv /home/scripts 
mv -f /home/wbmn-scripts-master/* /home/scripts
rm -rf /home/wbmn-scripts-master*
rsync -a /home/scriptsbkup/* /home/scripts
rmdir /home/scriptsbkup
find /home/scripts* -type f -print0 | xargs -0 chmod 777 

#####
