#!/bin/bash

#set -x
if [ -d /home/scripts ]; 
then 
#create scriptsbkup
mkdir /home/scriptsbkup;
else 
    echo "============================================"
		echo "scripts folder doesn't exist, mkdir scripts.."
		echo "============================================";
fi
mv -f /home/scripts /home/scriptsbkup 
rm -rf /home/scripts*
mkdir /home/scripts 
cd /home 
wget https://github.com/bigcloudcms/wbmn-scripts/archive/master.tar.gz && tar xfz master.tar.gz && rm -f master.tar.gz 
mv -f /home/wbmn-scripts-master/* /home/scripts
rm -rf /home/wbmn-scripts-master* 
find /home/scripts* -type f -print0 | xargs -0 chmod 777 

#####
