#!/bin/bash

#set -x

cd /home 
&& wget https://github.com/bigcloudcms/wbmn-scripts/archive/master.tar.gz && tar xfz master.tar.gz && rm -f master.tar.gz 
&& mkdir /home/scripts 
&& mv -f /home/wbmn-scripts-master/* /home/scripts 
&& rm -rf /home/wbmn-scripts-master*
&& find /home/scripts* -type f -print0 | xargs -0 chmod 777 
&& cd /home/admin/web/wpmaster.bigcloudcms.com/public_html/wp-content/themes/ 
&& wget https://github.com/bigcloudcms/wpcloudcms/archive/master.tar.gz && tar xfz master.tar.gz && rm -f master.tar.gz

#####
