#!/bin/bash

#set -x

mv -f /home/$client/web/$site/public_html/wp-config.php /home/$client/web/$site/tmp
mv -f /home/$client/web/$site/public_html/wp-content/uploads /home/$client/web/$site/tmp
mv -f /home/$client/web/$site/public_html/wp-content/themes /home/$client/web/$site/tmp
mv -f /home/$client/web/$site/public_html/wp-content/plugins /home/$client/web/$site/tmp

cd /home/$client/web/$site/tmp
tar -zcvf upload.tar.gz uploads/ && tar -zcvf themes.tar.gz themes/ && tar -zcvf plugins.tar.gz plugins/

rm -rf /home/$client/web/$site/public_html* 
  
mkdir /home/$client/web/$site/public_html 

mv -f /home/$client/web/$site/tmp/wp-config.php /home/$client/web/$site/public_html/

cd /home/$client/web/$site/public_html
wget http://wordpress.org/latest.tar.gz && tar xfz latest.tar.gz 

mv -f wordpress/* ./ && rmdir ./wordpress/ && rm -f latest.tar.gz 

cd /home/$client/web/$site

mv -f /tmp/uploads.tar.gz /public_html/wp-content/ && tar xfz uploads.tar.gz -C /public_html/wp-content/
mv -f /tmp/themes.tar.gz /public_html/wp-content/ #&& tar xfz themes.tar.gz -c /public_html/wp-content/
mv -f /tmp/plugins.tar.gz /public_html/wp-content/ && tar xfz plugins.tar.gz -c /public_html/wp-content/
rm -rf /home/$client/web/$site/tmp*

rm -rf /home/$client/web/$site/public_html/wp-content/themes/twentyfourteen* 
rm -rf /home/$client/web/$site/public_html/wp-content/themes/twentythirteen* 

rsync -avz /home/admin/web/wpmaster.bigcloudcms.com/public_html/wp-content/themes/virtue_premium/ /home/$client/web/$site/public_html/wp-content/themes/virtue_premium/ 
rsync -avz /home/admin/web/wpmaster.bigcloudcms.com/public_html/wp-content/plugins/ /home/$client/web/$site/public_html/wp-content/plugins/

cd /home/$client/web/$site/public_html/wp-content/themes/ 
wget https://github.com/bigcloudcms/wpcloudcms/archive/master.tar.gz && tar xfz master.tar.gz && rm -f master.tar.gz

find /home/$client/web/$site/public_html -type d -print0 | xargs -0 chmod 755 && find /home/$client/web/$site/public_html -type f -print0 | xargs -0 chmod 644 && find /home/$client/web/$site/public_html/wp-config-sample.php -type f -print0 | xargs -0 chmod 775 && chown -R $client:$client /home/$client/web/
           
#####
