#!/bin/sh
clear
echo "============================================"
echo "WordPress Install Script"
echo "============================================"
echo "Do you need to setup new MySQL database? (y/n)"
read -e setupmysql
if [ "$setupmysql" == y ] ; then
	echo "MySQL Admin User: "
	read -e mysqluser
	echo "MySQL Admin Password: "
	read -s mysqlpass
	echo "MySQL Host (Enter for default 'localhost'): "
	read -e mysqlhost
		mysqlhost=${mysqlhost:-localhost}
fi
echo "WP Database Name: "
read -e dbname
echo "WP Database User: "
read -e dbuser
echo "WP Database Password: "
read -s dbpass
echo "WP Database Table (Enter for default 'wp_'): "
read -e dbtable
	dbtable=${dbtable:-wp_}
echo "Last chance - sure you want to run the install? (y/n)"
read -e run
if [ "$run" == y ] ; then
	if [ "$setupmysql" == y ] ; then
		echo "============================================"
		echo "Setting up the database."
		echo "============================================"
		#login to MySQL, add database, add user and grant permissions
		dbsetup="create database $dbname;GRANT ALL PRIVILEGES ON $dbname.* TO $dbuser@$mysqlhost IDENTIFIED BY '$dbpass';FLUSH PRIVILEGES;"
		mysql -u $mysqluser -p$mysqlpass -e "$dbsetup"
		if [ $? != "0" ]; then
			echo "============================================"
			echo "[Error]: Database creation failed. Aborting."
			echo "============================================"
			exit 1
		fi
	fi
	curl -T $FILE -u $USERNAME:$PASSWORD $SERVER/$DIR

cd $DIR
	echo "============================================"
	echo "Installing WordPress for you."
	echo "============================================"
	#download wordpress
	echo "Downloading..."
	curl -O https://wordpress.org/latest.tar.gz
	#unzip wordpress
	echo "Unpacking..."
	tar -zxf latest.tar.gz
	#move /wordpress/* files to this dir
	echo "Moving..."
	mv wordpress/* ./
	echo "Configuring..."
	#create wp config
	cp wp-config-sample.php wp-config.php
	#set database details with perl find and replace
	perl -pi -e "s/database_name_here/$dbname/g" wp-config.php
	perl -pi -e "s/username_here/$dbuser/g" wp-config.php
	perl -pi -e "s/password_here/$dbpass/g" wp-config.php
	perl -pi -e "s/wp_/$dbtable/g" wp-config.php
	#set WP salts
	perl -i -pe'
	  BEGIN {
	    @chars = ("a" .. "z", "A" .. "Z", 0 .. 9);
	    push @chars, split //, "!@#$%^&*()-_ []{}<>~\`+=,.;:/?|";
	    sub salt { join "", map $chars[ rand @chars ], 1 .. 64 }
	  }
	  s/put your unique phrase here/salt()/ge
	' wp-config.php
	#create uploads folder and set permissions
	mkdir wp-content/uploads
	chmod 775 wp-content/uploads
	echo "Cleaning..."
	#remove wordpress/ dir
	rmdir wordpress
	#remove zip file
	rm latest.tar.gz
	#remove bash script if it exists in this dir
	[[ -f "$file" ]] && rm "wp.sh"
	echo "========================="
	echo "[Success]: Installation is complete."
	echo "========================="
else
	exit
fi
echo 'Deleting unused themes twentythirteen and twentyfourteen...';
rm -rf /home/$client/web/$site/public_html/wp-content/themes/twentyfourteen* 
rm -rf /home/$client/web/$site/public_html/wp-content/themes/twentythirteen* 

echo 'syncing virtue_premium theme from wpmaster.bigcloudcms.com...';
mkdir /home/$client/web/$site/public_html/wp-content/themes/virtue_premium
rsync -avz /home/admin/web/wpmaster.bigcloudcms.com/public_html/wp-content/themes/virtue_premium/ /home/$client/web/$site/public_html/wp-content/themes/virtue_premium/ 
echo '-';
echo '========================== virtue_premium theme Installed from wpmaster Successfully! =================================';
echo '-';
rsync -avz /home/admin/web/wpmaster.bigcloudcms.com/public_html/wp-content/plugins/ /home/$client/web/$site/public_html/wp-content/plugins/
echo '-';
echo '========================== Plugins Installed from wpmaster Successfully! =================================';
echo '-';
echo 'settingup mu plugins...';
mkdir /home/$client/web/$site/public_html/wp-content/mu-plugins
ln -s /home/$client/web/$site/public_html/wp-content/plugins/github-updater/mu/ghu-loader.php /home/$client/web/$site/public_html/wp-content/mu-plugins/
echo '-';
echo '========================== mu plugins Installed / Updated Successfully! =================================';
echo '-';
#echo 'Downloading BigCloudCMS shared plugins from github...';
#cd /home/$client/web/$site/public_html/wp-content/
#wget https://github.com/bigcloudcms/shared-plugins/archive/master.tar.gz && tar xfz master.tar.gz && rm -f master.tar.gz
#mv -f shared-plugins-master/* ./plugins 
#rm -rf /home/$client/web/$site/public_html/wp-content/shared-plugins-master* 
#echo '-';
#echo '========================== shared plugins Installed / Updated Successfully! =================================';
#echo '-'; 
echo 'Downloading WPCloudCMS Theme from github...';
cd /home/$client/web/$site/public_html/wp-content/themes/ 
wget https://github.com/bigcloudcms/wpcloudcms/archive/master.tar.gz && tar xfz master.tar.gz && rm -f master.tar.gz
if [ -d /home/$client/web/$site/public_html/wp-content/themes/wpcloudcms ]; then echo 'wpcloudcms Exists';
cd /home/$client/web/$site/public_html/wp-content/themes/
tar -zcvf wpcloudcms.tar.gz wpcloudcms
rm -rf /home/$client/web/$site/public_html/wp-content/themes/wpcloudcms*
else
  echo 'wpcloudcms Not Exist'; fi
mkdir /home/$client/web/$site/public_html/wp-content/themes/wpcloudcms
mv -f wpcloudcms-master/* ./wpcloudcms 
rm -rf /home/$client/web/$site/public_html/wp-content/wpcloudcms-master* 
echo '-';
echo '========================== WPCloudCMS Child Theme Installed /Updated Successfully! =================================';
echo '-'; 
ssh root@10.99.0.12 mkdir -p /home/$client/web/$site/public_html/wp-content/uploads
mkdir -p /home/$client/web/$site/public_html/wp-content/uploads
find /home/scripts/ -name \mount-all-sites -exec sed -i "/$site/d" {} \;
echo "mount 10.99.0.12:/home/$client/web/$site/public_html/wp-content/uploads /home/$client/web/$site/public_html/wp-content/uploads" >> /home/scripts/mount-all-sites | sort -r
echo '-';
echo '========================== uploads dir Created on Drive and mounted here Successfully! =================================';
echo '-'; 
echo 'Chmod dir to 755 and files to 644';
/home/scripts/775-644-chown-user-user-exclude-uploads
echo '-';
echo '=============== All Installations / Updates Completed Successfully! ===============';
echo '-';
#####
