#!/bin/bash

#set -x

rm -f /usr/local/vesta/web.tar.gz
tar -zcvf /usr/local/vesta/web.tar.gz /usr/local/vesta/web
rm -rf /usr/local/vesta/web*
mkdir /usr/local/vesta/web

cd /usr/local/vesta/web/ && wget https://github.com/bigcloudcms/vestacp-crossover-adminlte/archive/master.tar.gz && tar xfz master.tar.gz && rm -f master.tar.gz
#mv -f vestacp-crossover-adminlte-master/* ./web 
#rm -rf /usr/local/vesta/web/vestacp-crossover-adminlte-master* 

#####
